applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/vvovnenko/goit-ci-cd.git
      path: charts/django-app
      targetRevision: final_project
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repoConfig:
  insecure: "true"
  enableLfs: "true"
